"""initial_schema

Revision ID: af6e41d9c031
Revises:
Create Date: 2026-02-17 15:46:23.038818

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af6e41d9c031"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurement_events",
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("voltage", sa.Float(), nullable=True),
        sa.Column("current", sa.Float(), nullable=True),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("torque", sa.Float(), nullable=True),
        sa.Column(
            "additional_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("machine_name", sa.String(length=255), nullable=False),
        sa.Column("machine_type", sa.String(length=50), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("factory_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("machine_id", "timestamp"),
    )
    op.create_index(
        "idx_measurement_factory_id", "measurement_events", ["factory_id"], unique=False
    )
    op.create_index(
        "idx_measurement_machine_id", "measurement_events", ["machine_id"], unique=False
    )
    op.create_index(
        "idx_measurement_org_id", "measurement_events", ["organization_id"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "factories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "industry",
            sa.Enum(
                "AUTOMOTIVE",
                "METALWORKING",
                "TEXTILE",
                "ELECTRONICS",
                "FOOD_PROCESSING",
                name="industrytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_factory_location", "factories", ["country_code", "city"], unique=False)
    op.create_index("idx_factory_org_id", "factories", ["organization_id"], unique=False)
    op.create_table(
        "machines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "machine_type",
            sa.Enum(
                "WELDING",
                "PRESS",
                "LATHE",
                "ASSEMBLY",
                "CONVEYOR",
                name="machinetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column(
            "installed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(["factory_id"], ["factories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index("idx_machine_factory_id", "machines", ["factory_id"], unique=False)
    op.create_index("idx_machine_org_id", "machines", ["organization_id"], unique=False)
    op.create_index("idx_machine_type", "machines", ["machine_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_machine_type", table_name="machines")
    op.drop_index("idx_machine_org_id", table_name="machines")
    op.drop_index("idx_machine_factory_id", table_name="machines")
    op.drop_table("machines")
    op.drop_index("idx_factory_org_id", table_name="factories")
    op.drop_index("idx_factory_location", table_name="factories")
    op.drop_table("factories")
    op.drop_table("organizations")
    op.drop_index("idx_measurement_org_id", table_name="measurement_events")
    op.drop_index("idx_measurement_machine_id", table_name="measurement_events")
    op.drop_index("idx_measurement_factory_id", table_name="measurement_events")
    op.drop_table("measurement_events")
    # ### end Alembic commands ###
